package com.example.theatre.features

object Constants {
    const val BASE_URL = "https://kudago.com/public-api/v1.3/"
    const val ID = "id"
    const val PUBLICATION_DATE = "publication_date"
    const val DATES = "dates"
    const val TITLE = "title"
    const val SHORT_TITLE = "short_title"
    const val SLUG = "slug"
    const val PLACE = "place"
    const val DESCRIPTION = "description"
    const val BODY_TEXT = "body_text"
    const val LOCATION = "location"
    const val CATEGORIES = "categories"
    const val TAGLINE = "tagline"
    const val AGE_RESTRICTION = "age_restriction"
    const val PRICE = "price"
    const val IS_FREE = "is_free"
    const val IMAGES = "images"
    const val FAVORITES_COUNT = "favorites_count"
    const val COMMENTS_COUNT = "comments_count"
    const val SITE_URL = "site_url"
    const val TAGS = "tags"
    const val PARTICIPANTS = "participants"
    const val EVENT_ID = "event_id"
    const val CTYPE = "ctype"
    const val AGENT_TYPE = "agent_type"
    const val PARTICIPATIONS = "participations"
    const val NAME = "name"
    const val ADDRESS = "address"
    const val TIMETABLE = "timetable"
    const val PHONE = "phone"
    const val IS_STUB = "is_stub"
    const val FOREIGN_URL = "foreign_url"
    const val COORDS = "coords"
    const val SUBWAY = "subway"
    const val IS_CLOSED = "is_closed"
    const val PLACE_ID = "place_id"
    const val AGENT_ID = "agent_id"
}